package studentevaluationsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Dell
 */
public class StudentHomePage extends javax.swing.JFrame {

    /**
     * Creates new form StudentHomePage
     */
    public StudentHomePage() {
        initComponents();
    }

    private static final String username = "root";
    private static final String password = "Aishwarya@456";
    private static final String database = "jdbc:mysql://localhost:3306/studentevaluationsystem";
    
    Connection con = null;
    PreparedStatement p =null,p1=null;
    ResultSet r =null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StudentHomePage");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Basic Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, 205, 39));

        jButton2.setText("Attandance");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 205, 39));

        jButton3.setText("Meetings");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 270, 205, 39));

        jButton4.setText("Grades");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 225, 205, 39));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setText("Student Evaluation System");

        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("jlabel");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pexels-content-prod-co-5594266.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StudentAttandence sa = new StudentAttandence();
        String name = jLabel1.getText();
        JTextField t1 = sa.getTextfield1();
        JTextField t2 = sa.getTextfield2();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(database,username,password);
            String sql = "select * from studentinfo where StudentRollno = ?";
            p=con.prepareStatement(sql);
            p.setString(1, name);
            
            r=p.executeQuery();
            
            if(r.next())
            {
                String add1 = r.getString("StudentAtt");
                String add2 = r.getString("StudentPer");
                t1.setText(add1);
                t2.setText(add2);
            }
            p.close();
            sa.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        sa.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        StudentGrades sg = new StudentGrades();
        
        String name = jLabel3.getText();
        
        JTextField imoop = sg.getTextfield1();
        JTextField impy = sg.getTextfield2();
        JTextField imcn = sg.getTextfield3();
        JTextField imcoa = sg.getTextfield4();
        JTextField tim = sg.getTextfield5();
        JTextField emoop = sg.getTextfield6();
        JTextField empy = sg.getTextfield7();
        JTextField emcn = sg.getTextfield8();
        JTextField emcoa = sg.getTextfield9();
        JTextField egoop = sg.getTextfield10();
        JTextField egpy = sg.getTextfield11();
        JTextField egcn = sg.getTextfield12();
        JTextField egcoa = sg.getTextfield13();
        JTextField tem = sg.getTextfield14();
        JTextField sgpa = sg.getTextfield15();
        JTextField pf = sg.getTextfield16();
        JTextField ovg = sg.getTextfield17();
        
        JTextArea sf = sg.getArea();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(database,username,password);
            String sql = "select * from studentgrades where StudentName = ?";
            p=con.prepareStatement(sql);
            p.setString(1, name);
            
            r=p.executeQuery();
            
            if(r.next())
            {
                String add1 = r.getString("IMoop");
                String add2 = r.getString("IMpy");
                String add3 = r.getString("IMcn");
                String add4 = r.getString("IMcoa");
                String add5 = r.getString("EMoop");
                String add6 = r.getString("EMpy");
                String add7 = r.getString("EMcn");
                String add8 = r.getString("EMcoa");
                String add9 = r.getString("OverallGrade");
                String add10 = r.getString("Sgpa");
                String add11 = r.getString("PassOrFail");
                String add12 = r.getString("FailedSubjects");
                int opim = Integer.parseInt(add1);
                int pyim = Integer.parseInt(add2);
                int cnim = Integer.parseInt(add3);
                int coaim = Integer.parseInt(add4);
                int opem = Integer.parseInt(add5);
                int pyem = Integer.parseInt(add6);
                int cnem = Integer.parseInt(add7);
                int coaem = Integer.parseInt(add8);
                
                int newarr[] = new int[4 + 1]; 
                String newarr1[] = new String[4 + 1]; 
                
                newarr[0]=opem;
                newarr[1]=pyem;
                newarr[2]=cnem;
                newarr[3]=coaem;
                
                for(int i=0;i<4;i++)
                {
                    if(newarr[i]>65)
                    {
                        newarr1[i]="A";
                    }
                    else if(newarr[i]>60 && newarr[i]<65)
                    {
                        newarr1[i]="B";
                    }
                    else if(newarr[i]>55 && newarr[i]<60)
                    {
                        newarr1[i]="C";
                    }
                    else if(newarr[i]>45 && newarr[i]<55)
                    {
                        newarr1[i]="D";
                    }
                    else if(newarr[i]>35 && newarr[i]<45)
                    {
                        newarr1[i]="E";
                    }
                    else
                    {
                        newarr1[i]="F";
                    }
                }
                
                egoop.setText(newarr1[0]);
                egpy.setText(newarr1[1]);
                egcn.setText(newarr1[2]);
                egcoa.setText(newarr1[3]);
                
                int im = opim+pyim+coaim+cnim;
                int em = opem+pyem+coaem+cnem;
                
                String str1 = Integer.toString(im); 
                String str2 = Integer.toString(em); 
                
                imoop.setText(add1);
                impy.setText(add2);
                imcn.setText(add3);
                imcoa.setText(add4);
                emoop.setText(add5);
                empy.setText(add6);
                emcn.setText(add7);
                emcoa.setText(add8);
                
                sgpa.setText(add10);
                ovg.setText(add9);
                pf.setText(add11);
                sf.setText(add12);
                
                tim.setText(str1);
                tem.setText(str2);
            }
            p.close();
            sg.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        sg.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentInfo si = new StudentInfo();
        String name = jLabel1.getText();
       
        JTextField t1 = si.getTextfield1();
        JTextField t2 = si.getTextfield2();
        JTextField t3 = si.getTextfield3();
        JTextField t4 = si.getTextfield4();
        JTextField t5 = si.getTextfield7();
        JTextField t6 = si.getTextfield8();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(database,username,password);
            String sql = "select * from studentinfo where StudentRollno = ?";
            p=con.prepareStatement(sql);
            p.setString(1, name);
            
            r=p.executeQuery();
            
            if(r.next())
            {
                String add1 = r.getString("StudentRollno");
                String add2 = r.getString("StudentDOB");
                String add3 = r.getString("StudentCourse");
                String add4 = r.getString("StudentName");
                String add5 = r.getString("StudentEmail");
                String add6 = r.getString("StudentPhno");
                t1.setText(add1);
                t2.setText(add2);
                t3.setText(add3);
                t4.setText(add4);
                t5.setText(add5);
                t6.setText(add6);
            }
            
            si.setVisible(true);
                
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        StudentMeetings sm = new StudentMeetings();
        String name = jLabel1.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(database,username,password);
            String sql = "select * from studentinfo where StudentRollno = ?";
            p=con.prepareStatement(sql);
            p.setString(1, name);
            
            r=p.executeQuery();
            while(r.next())
            {
                String add1 = r.getString("StudentPer");
   
                double str1 = Double.parseDouble(add1);
                JLabel l = sm.getlabel1();
                if(str1<75.0)
                {
                    l.setText("you have a meeting with lecturer since you got less than 75% Attandance");
                }
                else
                {
                    l.setText("--------------------------------NONE--------------------------------");
                }
            }
            
            sm.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(StudentHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        sm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mainscreen m = new mainscreen();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    public JLabel getlabel()
    {
        return jLabel1;
    }
    public JLabel getlabel1()
    {
        return jLabel3;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
