package studentevaluationsystem;
        
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Dell
 */
public class StudentsInformation extends javax.swing.JFrame {

    /**
     * Creates new form StudentsInformation
     */
    private static final String username = "root";
    private static final String password = "Aishwarya@456";
    private static final String database = "jdbc:mysql://localhost:3306/studentevaluationsystem";
    
    Connection con = null;
    PreparedStatement p =null;
    ResultSet r =null;
    
            
    public StudentsInformation() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Stuname = new javax.swing.JLabel();
        Sturoll = new javax.swing.JLabel();
        Stucourse = new javax.swing.JLabel();
        Stuemail = new javax.swing.JLabel();
        Stuphno = new javax.swing.JLabel();
        StuNametf = new javax.swing.JTextField();
        Sturolltf = new javax.swing.JTextField();
        Stucoursetf = new javax.swing.JTextField();
        Stuemailtf = new javax.swing.JTextField();
        Stuphnotf = new javax.swing.JTextField();
        Studob = new javax.swing.JLabel();
        Studobtf = new javax.swing.JTextField();
        Att = new javax.swing.JLabel();
        Atttxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UpdateStudentInfo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,80));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Student Evaluation System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));

        Stuname.setText("Enter Student Name:");

        Sturoll.setText("Enter Student Rollno:");

        Stucourse.setText("Enter Student Course:");

        Stuemail.setText("Enter Student Email:");

        Stuphno.setText("Enter Student Phno:");

        StuNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuNametfActionPerformed(evt);
            }
        });

        Stucoursetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StucoursetfActionPerformed(evt);
            }
        });

        Studob.setText("Enter Student DOB:");

        Studobtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudobtfActionPerformed(evt);
            }
        });

        Att.setText("Enter the no of classes the student is present(out of 150):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Stuemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Stuemailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sturoll)
                            .addComponent(Stuname)
                            .addComponent(Studob)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Att)
                                    .addComponent(Stuphno))
                                .addGap(8, 8, 8))
                            .addComponent(Stucourse))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StuNametf, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(Sturolltf))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Stucoursetf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Studobtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stuphnotf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Atttxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stuname)
                    .addComponent(StuNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sturoll)
                    .addComponent(Sturolltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stucourse)
                    .addComponent(Stucoursetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Studob)
                    .addComponent(Studobtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stuemail)
                    .addComponent(Stuemailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stuphnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stuphno))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Att)
                    .addComponent(Atttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,80));

        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Print Student Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 400, 211));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student Name", "Student ID", "Student Course", "Date of Birth", "Student Email", "Telephone no", "Attandance"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 760, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pexels-cottonbro-5124882.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1030, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StucoursetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StucoursetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StucoursetfActionPerformed

    private void StuNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StuNametfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(Atttxt.getText());
        if(StuNametf.getText().isEmpty() || Sturolltf.getText().isEmpty() ||Stucoursetf.getText().isEmpty() || Studobtf.getText().isEmpty() ||Stuemailtf.getText().isEmpty() ||Stuphnotf.getText().isEmpty() ||Atttxt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(StudentsInformation.this, "Enter All Fields");
        }
        else if(a>150 || a<0)
        {
            JOptionPane.showMessageDialog(StudentsInformation.this, "Enter Valid Information");
        }
        else
        {
            int att = Integer.parseInt(Atttxt.getText());
            double per = (att*100)/150;
            String str = Double.toString(per);
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection(database,username,password);
                p = con.prepareStatement("insert into studentinfo(StudentName,StudentRollno,StudentCourse,StudentDOB,StudentEmail,StudentPhno,StudentAtt,StudentPer)value(?,?,?,?,?,?,?,?)");
                p.setString(1,StuNametf.getText());
                p.setString(2,Sturolltf.getText());
                p.setString(3,Stucoursetf.getText());
                p.setString(4,Studobtf.getText());
                p.setString(5,Stuemailtf.getText());
                p.setString(6,Stuphnotf.getText());
                p.setString(7,Atttxt.getText());
                p.setString(8,str);
               
                p.executeUpdate();

                String s = "insert into studentgrades(StudentName)value(?)";

                PreparedStatement p1 = con.prepareStatement(s);
                    p1.setString(1,StuNametf.getText());
                    p1.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record Added");
                jButton6.doClick();
                jButton4.doClick();
            }
            catch(ClassNotFoundException | SQLException e)
            {
                java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        StuNametf.setText("");
        Stucoursetf.setText("");
        Studobtf.setText("");
        Stuemailtf.setText("");
        Stuphnotf.setText("");
        Sturolltf.setText("");
        Atttxt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StudobtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudobtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudobtfActionPerformed

private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Conform if you want to exit","MySQL Connecter",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedrows = jTable1.getSelectedRow();
        try
        {
            int att = Integer.parseInt(Atttxt.getText());
            double per = (att*100)/150;
            String str = Double.toString(per);
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(database,username,password);
            p = con.prepareStatement("update studentinfo set StudentName = ?,StudentRollno = ?,StudentCourse = ?,StudentDOB = ?,StudentEmail = ?,StudentPhno = ?,StudentAtt = ?,StudentPer = ? where StudentName = ? ");
            p.setString(1,StuNametf.getText());
            p.setString(2,Sturolltf.getText());
            p.setString(3,Stucoursetf.getText());
            p.setString(4,Studobtf.getText());
            p.setString(5,Stuemailtf.getText());
            p.setString(6,Stuphnotf.getText());
            p.setString(7,Atttxt.getText());
            p.setString(8,str);
            p.setString(9,StuNametf.getText());
            
            
            p.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Updated");
            jButton6.doClick();
            jButton4.doClick();
        }
        catch(ClassNotFoundException e)
        {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
        }
        catch(SQLException e)
        {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedrows = jTable1.getSelectedRow();
        StuNametf.setText(model.getValueAt(selectedrows, 1).toString());
        Sturolltf.setText(model.getValueAt(selectedrows, 2).toString());
        Stucoursetf.setText(model.getValueAt(selectedrows, 3).toString());
        Studobtf.setText(model.getValueAt(selectedrows, 4).toString());
        Stuemailtf.setText(model.getValueAt(selectedrows, 5).toString());
        Stuphnotf.setText(model.getValueAt(selectedrows, 6).toString());
        Atttxt.setText(model.getValueAt(selectedrows, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0); 
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection(database,username,password);
            try (Statement stmt = con.createStatement()) {
                ResultSet rs = stmt.executeQuery("SELECT * FROM STUDENTINFO");
                while(rs.next())
                {
                    int id = rs.getInt("ID");
                    String name = rs.getString("StudentName");
                    String rollno = rs.getString("StudentRollno");
                    String course = rs.getString("StudentCourse");
                    String dob = rs.getString("StudentDOB");
                    String email = rs.getString("StudentEmail");
                    String phno = rs.getString("StudentPhno");
                    String att = rs.getString("StudentAtt");
                    model.addRow(new Object[]{id,name,rollno,course,dob,email,phno,att});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentsInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String name = jTable1.getValueAt(row,1).toString();
        
        String stmt = "delete from studentinfo where StudentName = ?";
        try {
            PreparedStatement s = con.prepareStatement(stmt);
            s.setString(1, name);
            s.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record Deleted");
            s.close();
            
            String stmt1 = "delete from studentgrades where StudentName = ?";
            PreparedStatement s1 = con.prepareStatement(stmt1);
            s1.setString(1, name);
            s1.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record Deleted");
            s.close();
            
            jButton6.doClick();
            jButton4.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(StudentsInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jButton6.doClick();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Att;
    private javax.swing.JTextField Atttxt;
    private javax.swing.JTextField StuNametf;
    private javax.swing.JLabel Stucourse;
    private javax.swing.JTextField Stucoursetf;
    private javax.swing.JLabel Studob;
    private javax.swing.JTextField Studobtf;
    private javax.swing.JLabel Stuemail;
    private javax.swing.JTextField Stuemailtf;
    private javax.swing.JLabel Stuname;
    private javax.swing.JLabel Stuphno;
    private javax.swing.JTextField Stuphnotf;
    private javax.swing.JLabel Sturoll;
    private javax.swing.JTextField Sturolltf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
